{"name": "test_login_empty_input", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './tests/csv/error_message.csv'", "trace": "self = <tests.test_login.TestLogin object at 0x10502a050>, driver = <appium.webdriver.webdriver.WebDriver (session=\"64dc9a41e27bb3a1b93ead5a7f349efd73dace8c\")>\n\n    @pytest.mark.login_negative\n    def test_login_empty_input(self, driver):\n        # Initialization\n>       self.init(driver)\n\ntests/test_login.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/test_login.py:22: in init\n    self.error = error_message()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def error_message():\n        error_dict = dict()\n>       with open(CSV_PATH, 'r', encoding='utf-8') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: './tests/csv/error_message.csv'\n\nhelpers/error_message.py:8: FileNotFoundError"}, "attachments": [{"name": "log", "source": "af94301d-cf5e-4e97-a431-24c663b25553-attachment.txt", "type": "text/plain"}], "start": 1693149594069, "stop": 1693149594069, "uuid": "305720d5-cb15-4f7a-bc0b-02fc852a219f", "historyId": "05603206456e4809964169438552e439", "testCaseId": "f352a75c52f7b26ebfd83a491ec0fff9", "fullName": "tests.test_login.TestLogin#test_login_empty_input", "labels": [{"name": "tag", "value": "login_negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ypetryk-MacBook-Pro.local"}, {"name": "thread", "value": "5833-0"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}