{"uuid": "0cd35325-2b51-415b-837e-804e908f6c22", "children": ["04ccfd03-b63d-4332-8fff-2d5b2e998a72"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: The property '#/alwaysMatch/bstack:options' contains additional properties [\"browserstack.devicePreferences\"] outside of the schema when none are allowed in the payload.\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/yaroslav.petryk/Desktop/projects/browserstack_appium/tests/conftest.py\", line 32, in driver\n    driver = webdriver.Remote(url, capabilities)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 257, in __init__\n    super().__init__(\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/browserstack_sdk/__init__.py\", line 1670, in bstack11llll11l_opy_\n    bstack1l1lll111_opy_(self, command_executor=command_executor,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 272, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 346, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1693208715705, "stop": 1693208716272}], "start": 1693208715705, "stop": 1693208716461}